sudo: required
dist: trusty
os:
- linux
notifications:
  email: true
script:
- ./make.sh
before_install:
- sudo apt-get -qq update 
env:
  global:
  - OUT_DIR: b/
  - TMP_DIR: tmp/
  - MODS: "jme,jme-frk" 